//
//  APIConstants.swift
//  Thoab App
//
//  Created by Arvind Valaki on 08/01/18.
//  Copyright © 2018 Thoab App. All rights reserved.
//

import Foundation

let BASE_URL = "https://ezarksa.com/" //Production

//let BASE_URL = "http://alnaseej.php-dev.in/" //Development


struct APIStatus {
    static let success = "Success"
}

struct API_URL {
    
    static let configuration                = "customapi/authentication/configuration"
    static let Login                        = "customapi/customer/login"
    static let register                     = "customapi/customer/registration"
    static let submitOtp                    = "customapi/submitOtp"
    static let sendotp                      = "customapi/customer/sendotp"
    static let resendOtp                    = "customapi/resendOtp"
    static let category                     = "customapi/catalog/categorylisting"
    static let exploreCategory              = "customapi/catalog/expmorecategory"
    static let promotions                   = "customapi/catalog/promotions"
    static let question                     = "customapi/question"
    static let forgetPassword               = "customapi/customer/forgotpassword"
    static let changePassword               = "customapi/customer/changepassword"
    static let searchSeller                 = "customapi/catalog/searchseller"
    static let vendorDetails                = "customapi/catalog/vendordetails"
    static let subCategoryListing           = "customapi/catalog/subcategorylisting"
    static let allReviews                   = "customapi/vendor/allreviews"
    static let productoptions               = "customapi/catalog/productoptions"
    static let productDetails               = "customapi/catalog/productdetails"
    static let editprofile                  = "customapi/customer/editprofile"
    static let myaccount                    = "customapi/customer/myaccount"
    static let catalogproducts              = "customapi/catalog/catalogproducts"
    static let myCart                       = "customapi/checkout/mycart"
    static let addToCart                    = "customapi/checkout/addtocart"
    static let availableShippingMethods     = "customapi/checkout/availableShippingMethods"
    static let deleteCartItem               = "customapi/checkout/deleteproductfromcart"
    static let measurements                 = "customapi/customer/measurements"
    static let measurementoptions           = "customapi/customer/measurementoptions"
    static let savemeasurement              = "customapi/customer/savemeasurement"
    static let updatemeasurement            = "customapi/customer/updatemeasurement"
    
    static let deletemeasurement            = "rest/default/V1/delete-measurement"
    static let placeorder                   = "customapi/checkout/placeorder"
    static let paymentmethodlisting         = "customapi/checkout/paymentmethodlisting"
    static let previousmeasurement          = "customapi/customer/PreviousMeasurement"
    static let tailorCatalogProducts        = "customapi/catalog/tailorCatalogProducts"
    static let updatecart                   = "customapi/checkout/updatecart"
    static let applyfabric                  = "customapi/checkout/applyfabric"
    static let fabricproductdetails         = "customapi/catalog/fabricproductdetails"
    static let fabriccatalogproducts        = "customapi/catalog/fabriccatalogproducts"
    static let customerRequest              = "customapi/delegate/CustomerRequest"
     static let customerResetPassword       = "customapi/customer/newpassword"
    static let customerRequestInformation   = "customapi/customer/requestinformation"
    static let getmeasurements              = "customapi/customer/getmeasurements"
    static let reviewsAndFeedback           = "customapi/reviews/reviewsAndFeedback"
    static let reviewsandfeedbackpagination = "customapi/reviews/reviewsandfeedbackpagination"
    static let message                      = "customapi/customer/message"
    static let reviews_add                  = "customapi/reviews/add"
    static let sendMessage                  = "customapi/sms/sendmessage"
    static let getorders                    = "customapi/customer/getorders"
    static let getallorders                 = "customapi/customer/getallorders"
    static let getrewardpoints              = "customapi/customer/getrewardpoints"
    static let addtofavourite               = "customapi/customer/addtofavourite"
    static let addtowishlist                = "customapi/customer/addtowishlist"
    static let getwishlist                  = "customapi/customer/getwishlist"
    static let getNotifications             = "customapi/customer/getnotifications"
    static let getaddress                   = "customapi/customer/getaddress"
    static let removeaddress                = "customapi/customer/removeaddress"
    static let reviewslikedislike           = "customapi/reviews/reviewslikedislike"
    static let removefromwishlist           = "customapi/customer/removefromwishlist"
    static let homeproductsearch            = "customapi/catalog/homeproductsearch"
    static let applyCoupon                  = "customapi/checkout/applycoupon"
    static let getOrderDetails              = "customapi/order/orderdetail"
    static let cancelOrder                  = "customapi/order/OrderCancel"
    static let updateMeasurement            = "customapi/order/OrderUpdate"
    static let helpDetails                  = "customapi/cms/helpdetails"
    static let faqDetails                   = "customapi/cms/faqdetails"
    static let delegate_sendotp             = "customapi/delegate/sendotp"
    static let shareUrl                     = "applications"
    static let orderReturn                  = "customapi/customer/orderreturn"
    static let myReturn                     = "customapi/customer/myreturn"
    static let returndetails                = "customapi/customer/returndetails"
    static let requestreply                 = "customapi/customer/requestreply"
    static let invitefriends                = "customapi/customer/invitefriends"
     static let getimages                    = "customapi/gallery/getimages"
    
    //delegate API
    static let delegateRegister             = "customapi/delegate/register"
    static let delegateLogin                = "customapi/delegate/login"
    static let delegateChangePassword       = "customapi/delegate/changepassword"
    static let delegateHomeRequest          = "customapi/delegate/delegaterequest"
    static let nearestdelegate              = "customapi/delegate/nearestdelegate"
    static let delegateDetail               = "customapi/delegate/delegatedetails"
    static let savedelegaterequest          = "customapi/delegate/savedelegaterequest"
    static let delegateEditProfile          = "customapi/delegate/editprofile"
    static let delegateRequestDetails       = "customapi/delegate/requestdetails"
    static let delegateAccount              = "customapi/delegate/myaccount"
    static let changeRequestStatus          = "customapi/delegate/changerequeststatus"
    static let delegateForgotPassword       = "customapi/delegate/forgotpassword"
    static let delegateResetPassword        = "customapi/delegate/newpassword"
    static let delegateUpdatelocation       = "customapi/delegate/updatelocation"
    static let delegateIsavailable          = "customapi/delegate/isavailable"
    //Pushnotification
    static let customerTokenUpdate          = "push_notification/customer/tokenupdate"
    static let delegateTokenUpdate          = "push_notification/delegates/tokenupdate"
    static let customerNotificationListURL  = "push_notification/customer/notificationbyid"
    static let DelegateNotificationListURL  = "push_notification/delegates/notificationbyid"
    static let orderList                = "customapi/delegate/orderslist"
    static let orderDetail              = "customapi/delegate/ordersdetails"
    static let transactionHistory              = "customapi/delegate/transactionlist"
    static let paymentHistory              = "customapi/delegate/paymenthistorylist"
    static let paymentHistoryDetail              = "customapi/delegate/paymenthistorydetail"
    static let savewithdrawform              = "customapi/delegate/savewithdrawform"
    static let cmspages              = "customapi/cms/pages"
    static let rewardHistory              = "customapi/customer/RewardPointHistory"
    static let broadCastList             = "customapi/delegate/BroadCastList"
    static let deleteBroadCastRequest            = "customapi/delegate/DeleteBroadCastRequest"
    static let bodymeasurementscanner            = "customapi/customer/bodymeasurementscanner"
    static let termsConditionScanner   = "customapi/cms/pages"
     static let bodyFit              = "customapi/customer/fitoptions"
}

struct API_KEYS {
    
    static let email                 = "email"
    static let social_type           = "social_type"
    static let social_login_id       = "social_login_id"
    static let password              = "password"
    static let name                  = "name"
    static let otp                   = "otp"
    static let confirm_password      = "confirm_password"
    static let password_confirmation = "password_confirmation"
    static let device_type           = "device_type"
    static let country_code          = "country_code"
    static let mobile_number         = "mobile_number"
    static let city                  = "city"
    static let root_category         = "root_category"
    static let product_type          = "product_type"
    static let new_password          = "new_password"
    static let old_password          = "old_password"
    static let fabric_offline        = "fabric_offline"
    static let rating                = "rating"
    static let description           = "description"
    static let review_id             = "review_id"
    static let review_description    = "review_description"
    static let review_title          = "review_title"
    static let question_answers      = "question_answers"
    static let is_remove             = "is_remove"
    static let is_subscribed         = "is_subscribed"
    
    //Search Keys
    static let category_id           = "category_id"
    static let delivery_date         = "delivery_date"
    static let longitude             = "longitude"
    static let latitude              = "latitude"
    static let qty                   = "qty"
    static let review_type           = "review_type"
    static let vendor_id             = "vendor_id"
    static let id                    = "id"
    static let total_reviews        = "total_reviews"
    static let search_string        = "search_string"
    static let reward_points        = "reward_points"
    
    //Productoptions Keys
    static let model_type           = "model_type"
    static let product_id           = "product_id"
    static let store_id             = "store_id"
    static let customer_id          = "customer_id"
    static let profile_image        = "profile_image"
    static let current_page         = "current_page"
    static let lang                 = "lang"
    static let sort                 = "sort"
    static let order_by             = "order_by"
    static let style                = "style"
    static let item_quote_id        = "item_quote_id"
    static let quote_id             = "quote_id"
    static let customer_type        = "customer_type"
    
    static let tailor_measurement   = "tailor_measurement"
    
    static let measurement_id       = "measurement_id"
    static let measurement_note       = "note"
    static let category_name        = "category_name"
    static let price                = "price"
    static let special_price        = "special_price"
    static let up_vote              = "up_vote"
    
    static let postcode             = "postcode"
    static let state                = "state"
    static let country              = "country"
    static let cart_item_collection = "cart_item_collection"
    static let measurement_type     = "measurement_type"
    static let shipping             = "shipping"
    static let payment              = "payment"
    static let discount             = "discount"
    static let tax                  = "tax"
    static let title                = "title"
    static let height               = "height"
    static let weight               = "weight"
    static let collar               = "collar"
    static let selected_type        = "selected_type"
    static let measurements         = "measurements"
    static let is_promotion         = "is_promotion"
    static let custom_tier_price    = "custom_tier_price"
    static let delegate_id          = "delegate_id"
    static let request_for          = "request_for"
    static let request_information  = "request_information"
    static let dob                  = "dob"
    static let request_id           = "request_id"
    static let customer_address     = "customer_address"
    static let status               = "status"
    static let faq_id               = "faq_id"
    static let user_type            = "user_type"
    static let measure_by           = "measure_by"
    static let message              = "message"
    static let is_customer          = "is_customer"
    static let is_seller          = "is_seller"
    static let is_favourite          = "is_favourite"
    static let address_id           = "address_id"
    static let order_item_id        = "order_item_id"
    static let is_default           = "is_default"
    static let location_type        = "location_type"
    static let country_name         = "country_name"
    static let street               = "street"
    static let type                 = "type"
    static let item_id              = "item_id"
    static let page_count           = "page_count"
    static let is_available         = "is_available"
    static let gift_wrap            = "gift_wrap"
    static let device_token         = "device_token"
    static let device_token_type    = "device_token_type"
    static let applied_reward_points    = "applied_reward_points"
    static let current_conversion_rate = "current_conversion_rate"
    static let rewards_converted_to_currency = "rewards_converted_to_currency"
    static let coupon_code = "coupon_code"
    static let order_id = "order_id"
    static let order_incremental_id = "order_incremental_id"
    static let order_items = "order_items"
    static let bank_name = "bank_name"
    static let account_no = "account_no"
    static let iban_no = "iban_no"
    static let language = "language"
    static let payment_id = " payment_id"
    static let amount = "amount"
    static let comment = "comment"
    static let commission = "commission"
    static let identifier = "identifier"
    static let request_instruction = "request_instruction"
    static let broadcast_id = "broadcast_id"
    static let reset = "reset"
    static let body_images = "body_images"
}
