-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGVPfICw9XkQP/C+5
k862kiKNtnG/Gi3+crDbFrunWQigCgYIKoZIzj0DAQehRANCAARBvRkgckhfg2Fp
ocdHBD+vfJq304RznxI8O4Lz6hdP+445+y9qaBaluUhgPNMCPFtkGOeE7PmOrV22
ZLyuOUpR
-----END PRIVATE KEY-----